### ISSUE TITLE
Dependency conflicts with CytoTable and `pandas==2.1.1`

### ISSUE THREAD

**Issue by d33bs** [cytomining/CytoTable#116]
> Additionally, I also encountered a package dependency issue. Specifically, the script was able to run when I uninstalled `pandas`, but gave an error when `pandas==2.1.1` is installed. I am not sure if others have encountered similar issues or if I did something wrong. Thank you!

_Originally mentioned by @Zitong-Chen-16 in https://github.com/cytomining/CytoTable/issues/105#issuecomment-1738081608_

**Comment by d33bs** [comment]
@Zitong-Chen-16 - I took a look at this and noticed the following error message when attempting to install `pandas==2.1.1` through the Poetry environment of CytoTable. Is this the same error you noticed?

```shell
The current project's Python requirement (>=3.8,<3.13) is not compatible with some of the required packages Python requirement:
  - pandas requires Python >=3.9, so it will not be satisfied for Python >=3.8,<3.9

Because cytotable depends on pandas (2.1.1) which requires Python >=3.9, version solving failed.
```

I believe this is a bug with the package Python version specifications. I could be misunderstanding, but this seems like it might be a misperception of Poetry on the version ranges required by CytoTable (Pandas required Python >= 3.9 should fall in the range of Python >=3.8, <3.13).

Depending on how you manage your environment, it might be possible to use PIP or other methods to circumvent the Poetry environment constraints (if this is what you're seeing). For example, using `pip install "cytotable==0.0.2" "pandas==2.1.1"` appears to work.

**Comment by Zitong-Chen-16** [comment]
Hi Dave, thank you for looking into this issue!

The problem I had was not with installing pandas though, I was able to install pandas after cytotable using pip install. My issue was that after pandas was installed, the script that was originally running successfully now failed to run with the following error message.

> Traceback (most recent call last):
  File "/dgx1nas1/storage/data/sam/codes/2021_09_01_VarChAMP/6.downstream_analysis/convert_to_parquet.py", line 121, in <module>
    convert(
  File "/dgx1nas1/storage/data/sam/.conda/envs/varchamp/lib/python3.11/site-packages/cytotable/convert.py", line 1434, in convert
    ).result()
      ^^^^^^^^
  File "/dgx1nas1/storage/data/sam/.conda/envs/varchamp/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/dgx1nas1/storage/data/sam/.conda/envs/varchamp/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/dgx1nas1/storage/data/sam/.conda/envs/varchamp/lib/python3.11/site-packages/parsl/dataflow/dflow.py", line 301, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dgx1nas1/storage/data/sam/.conda/envs/varchamp/lib/python3.11/site-packages/parsl/dataflow/dflow.py", line 573, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/dgx1nas1/storage/data/sam/.conda/envs/varchamp/lib/python3.11/site-packages/parsl/app/errors.py", line 122, in reraise
    reraise(t, v, v.__traceback__)
  File "/dgx1nas1/storage/data/sam/.conda/envs/varchamp/lib/python3.11/site-packages/six.py", line 719, in reraise
    raise value
  File "/dgx1nas1/storage/data/sam/.conda/envs/varchamp/lib/python3.11/site-packages/parsl/app/errors.py", line 145, in wrapper
    return func(*args, **kwargs)
^^^^^^^^^^^^^^^
  File "/dgx1nas1/storage/data/sam/.conda/envs/varchamp/lib/python3.11/site-packages/cytotable/convert.py", line 1094, in _to_parquet
    ).result()
      ^^^^^^^^^
  File "/dgx1nas1/storage/data/sam/.conda/envs/varchamp/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
^^^^^^^
  File "/dgx1nas1/storage/data/sam/.conda/envs/varchamp/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
^^^^^^^^^^^
parsl.dataflow.errors.JoinError: Join failure for task 1 with failed join dependencies from tasks [5]


I am wondering were you able to run the convert function successfully after installing pandas==2.1.1 ?

**Comment by d33bs** [comment]
Hi @Zitong-Chen-16, thank you for the additional details here! Referencing the trace logs you shared I tried to reproduce this error using conda, Python 3.11, Pandas 2.1.1, and CytoTable 0.0.2. There were two issues I ran into which needed resolution in order to run CytoTable:

- I initially noticed Numpy errors through PyArrow. These were resolved by adding Numpy as an explicit conda dependency. I believe this might have something to do with how conda builds references to dependencies from pip vs conda, but I'm not absolutely certain.
- I also noticed that changes in recent versions of Parsl caused the workflows to halt. This can be worked around by setting a static earlier version reference. This is addressed moving forward via #112 .

Here's an example of the `env.yml` I used to run testing:
```yaml
name: cytotable_116
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas=2.1.1
  - numpy
  - pip:
    - cytotable>=0.0.2
    - parsl==2023.09.18
```

In addition, here's a [full reference](https://gist.github.com/d33bs/bb6af204fe779c05a0ca029aae022f4a) to how I performed testing.

Does this look similar to your environment or what you're seeing? Please don't hesitate to let me know if you have any questions or if there's something we can do to change the approach for troubleshooting with this. Thank you for your help in addressing this!
